name: Deploy website
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: echo the password
      run: echo ${{secrets.PASSWORD}}
      
