name: Deploy website
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Get Code
       uses: actions/checkout@v3
     - name: echo the password
       run: echo ${{secrets.PASSWORD}}
      
